# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e1c0aa995f527113f9530dd23acb23b7cdc104e5b5e5c0a4269bc6ca166e474b3d41f88f485a398754894127f879f8b2dc5a9af87c8202cf1f1d858305f221

test:
  secret_key_base: 49099112b4785c4ba9b1668c31acf6085dcfb210ccbe16d3ab417f8b038a8954228a3381c5d9646494f1b1b4864758c51f7e2c051e37f4abab6c082df86d67f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
